// <auto-generated />
using System;
using GMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GMS.Entities.Models.AutentifikacijaToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("KorisnickiNalogId")
                        .HasColumnType("int");

                    b.Property<string>("ipAdresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vrijednost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("vrijemeEvidentiranja")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("KorisnickiNalogId");

                    b.ToTable("AutentifikacijaToken");
                });

            modelBuilder.Entity("GMS.Entities.Models.Clanarina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<float>("Cijena")
                        .HasColumnType("real");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Clanarina");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Cijena = 50f,
                            Naziv = "Fit Plus",
                            Opis = "Teretane predstavljaju oazu zdravlja pružajući nam prostor gdje možemo ojačati svoje tijelo i smanjiti stres. Članstvo u teretani nije samo ulaganje u tjelesno zdravlje već i putovanje prema boljoj verziji sebe."
                        },
                        new
                        {
                            ID = 2,
                            Cijena = 40f,
                            Naziv = "Student Fit Plus",
                            Opis = "Studentska članarina u teretani nije samo investicija u tjelesno zdravlje, već i u opću dobrobit studenata. Zahvaljujući ovim povlasticama, teretane postaju pristupačne za studente svih financijskih mogućnosti, čime se stvara zdraviji i sretniji studentski život. Zbog toga mi nudimo popust od čak 20% za sve studente!"
                        },
                        new
                        {
                            ID = 3,
                            Cijena = 25f,
                            Naziv = "Partner Fit Duo",
                            Opis = "Teretane nude posebne članarine za parove koje omogućuju partnerima da zajedno uživaju u prednostima vježbanja. Podijelite iznos jedne članarine i uživajte u jačanju tijela i uma!"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Dobavljac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Dobavljac");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Naziv = "MUSCLE FREAK"
                        },
                        new
                        {
                            ID = 2,
                            Naziv = "MUSCLETECH"
                        },
                        new
                        {
                            ID = 3,
                            Naziv = "OPTIMUM NUTRITION"
                        },
                        new
                        {
                            ID = 4,
                            Naziv = "SELF OMNINUTRITION"
                        },
                        new
                        {
                            ID = 5,
                            Naziv = "CW-CHEMICAL WARFARE"
                        },
                        new
                        {
                            ID = 6,
                            Naziv = "BSN"
                        },
                        new
                        {
                            ID = 7,
                            Naziv = "CELLUCOR"
                        },
                        new
                        {
                            ID = 8,
                            Naziv = "EVOLITE"
                        },
                        new
                        {
                            ID = 9,
                            Naziv = "SUPERIOR"
                        },
                        new
                        {
                            ID = 10,
                            Naziv = "TESLA"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.FAQ", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Odgovor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pitanje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FAQ");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Odgovor = "Cijene mjesečnih članarina variraju ovisno o paketu koji odaberete. Imamo različite opcije  prilagođene različitim potrebama i budžetima. Detaljne informacije o cijenama možete pronaći na homepage pod sekcijom 'cjenovnik članarina'.",
                            Pitanje = "Koliko košta članarina u vašoj teretani?"
                        },
                        new
                        {
                            ID = 2,
                            Odgovor = "Da, imamo stručne trenere koji vam mogu pomoći u postizanju vaših fitness ciljeva. Oni će raditi s vama kako bi razvili personalizirani plan vježbanja. Pored njih, imamo i naš tim nutricionista.",
                            Pitanje = "Da li u sklopu teretane imate personalne trenere?"
                        },
                        new
                        {
                            ID = 3,
                            Odgovor = "Vrlo jednostavno! Posjetite našu recepciju, odaberite željeni paket i dobit ćete svoju člansku karticu!",
                            Pitanje = "Kako da postanem član vaše teretane?"
                        },
                        new
                        {
                            ID = 4,
                            Odgovor = "Tačnu lokaciju naše teretane možete pogledati na homepage pod rubrikom 'kako do nas?'.",
                            Pitanje = "Gdje se nalazi vaša teretana?"
                        },
                        new
                        {
                            ID = 5,
                            Odgovor = "Kupovinu suplemenata izvršavate putem sekcije suplementi, pomoću koje rezervišete vas proizvod koji nakon toga trebate preuzeti u našoj poslovnici te platiti po uzeću.",
                            Pitanje = "Kako izvršiti kupovinu suplemenata?"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Grad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Grad");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Naziv = "Banja Luka"
                        },
                        new
                        {
                            ID = 2,
                            Naziv = "Bihać"
                        },
                        new
                        {
                            ID = 3,
                            Naziv = "Bijeljina"
                        },
                        new
                        {
                            ID = 4,
                            Naziv = "Bosnaska Krupa"
                        },
                        new
                        {
                            ID = 5,
                            Naziv = "Cazin"
                        },
                        new
                        {
                            ID = 6,
                            Naziv = "Čapljina"
                        },
                        new
                        {
                            ID = 7,
                            Naziv = "Drventa"
                        },
                        new
                        {
                            ID = 8,
                            Naziv = "Doboj"
                        },
                        new
                        {
                            ID = 9,
                            Naziv = "Goražde"
                        },
                        new
                        {
                            ID = 10,
                            Naziv = "Gračanica"
                        },
                        new
                        {
                            ID = 11,
                            Naziv = "Gradačac"
                        },
                        new
                        {
                            ID = 12,
                            Naziv = "Gradiška"
                        },
                        new
                        {
                            ID = 13,
                            Naziv = "Konjic"
                        },
                        new
                        {
                            ID = 14,
                            Naziv = "Laktaši"
                        },
                        new
                        {
                            ID = 15,
                            Naziv = "Livno"
                        },
                        new
                        {
                            ID = 16,
                            Naziv = "Lukavac"
                        },
                        new
                        {
                            ID = 17,
                            Naziv = "Ljubuški"
                        },
                        new
                        {
                            ID = 18,
                            Naziv = "Mostar"
                        },
                        new
                        {
                            ID = 19,
                            Naziv = "Orašje"
                        },
                        new
                        {
                            ID = 20,
                            Naziv = "Prijedor"
                        },
                        new
                        {
                            ID = 21,
                            Naziv = "Prnjavor"
                        },
                        new
                        {
                            ID = 22,
                            Naziv = "Sarajevo"
                        },
                        new
                        {
                            ID = 23,
                            Naziv = "Srebrenik"
                        },
                        new
                        {
                            ID = 24,
                            Naziv = "Stolac"
                        },
                        new
                        {
                            ID = 25,
                            Naziv = "Široki Brijeg"
                        },
                        new
                        {
                            ID = 26,
                            Naziv = "Travnik"
                        },
                        new
                        {
                            ID = 27,
                            Naziv = "Tuzla"
                        },
                        new
                        {
                            ID = 28,
                            Naziv = "Visoko"
                        },
                        new
                        {
                            ID = 29,
                            Naziv = "Zavidovići"
                        },
                        new
                        {
                            ID = 30,
                            Naziv = "Zenica"
                        },
                        new
                        {
                            ID = 31,
                            Naziv = "Zvornik"
                        },
                        new
                        {
                            ID = 32,
                            Naziv = "Živinice"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Kategorija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kategorija");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Naziv = "Proteini"
                        },
                        new
                        {
                            ID = 2,
                            Naziv = "Amino kiseline"
                        },
                        new
                        {
                            ID = 3,
                            Naziv = "Preworkout"
                        },
                        new
                        {
                            ID = 4,
                            Naziv = "Mass gaineri"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.KorisnickiNalog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KorisnickiNalog");

                    b.HasDiscriminator<string>("Discriminator").HasValue("KorisnickiNalog");
                });

            modelBuilder.Entity("GMS.Entities.Models.Korisnik_Clanarina", b =>
                {
                    b.Property<int>("ClanarinaID")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumUplate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.HasKey("ClanarinaID", "KorisnikID", "DatumUplate");

                    b.HasIndex("KorisnikID");

                    b.ToTable("Korisnik_Clanarina");

                    b.HasData(
                        new
                        {
                            ClanarinaID = 2,
                            KorisnikID = 3,
                            DatumUplate = new DateTime(2023, 9, 1, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            DatumIsteka = new DateTime(2023, 10, 1, 9, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClanarinaID = 2,
                            KorisnikID = 4,
                            DatumUplate = new DateTime(2023, 9, 1, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            DatumIsteka = new DateTime(2023, 10, 1, 9, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClanarinaID = 2,
                            KorisnikID = 3,
                            DatumUplate = new DateTime(2023, 10, 1, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            DatumIsteka = new DateTime(2023, 11, 1, 7, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClanarinaID = 2,
                            KorisnikID = 4,
                            DatumUplate = new DateTime(2023, 10, 1, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            DatumIsteka = new DateTime(2023, 11, 1, 7, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClanarinaID = 1,
                            KorisnikID = 5,
                            DatumUplate = new DateTime(2023, 10, 1, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            DatumIsteka = new DateTime(2023, 11, 1, 7, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClanarinaID = 1,
                            KorisnikID = 6,
                            DatumUplate = new DateTime(2023, 10, 1, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            DatumIsteka = new DateTime(2023, 11, 1, 7, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClanarinaID = 1,
                            KorisnikID = 7,
                            DatumUplate = new DateTime(2023, 10, 1, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            DatumIsteka = new DateTime(2023, 11, 1, 7, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClanarinaID = 2,
                            KorisnikID = 3,
                            DatumUplate = new DateTime(2023, 11, 1, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            DatumIsteka = new DateTime(2023, 12, 1, 7, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClanarinaID = 2,
                            KorisnikID = 4,
                            DatumUplate = new DateTime(2023, 11, 1, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            DatumIsteka = new DateTime(2023, 12, 1, 7, 15, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Korisnik_Nutricionist", b =>
                {
                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int>("NutricionistID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumTermina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OdrzanoSati")
                        .HasColumnType("datetime2");

                    b.HasKey("KorisnikID", "NutricionistID", "DatumTermina");

                    b.HasIndex("NutricionistID");

                    b.ToTable("Korisnik_Nutricionst");
                });

            modelBuilder.Entity("GMS.Entities.Models.Korisnik_Suplement", b =>
                {
                    b.Property<int>("SuplementID")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumVrijemeNarudzbe")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.HasKey("SuplementID", "KorisnikID", "DatumVrijemeNarudzbe");

                    b.HasIndex("KorisnikID");

                    b.ToTable("Korisnik_Suplement");
                });

            modelBuilder.Entity("GMS.Entities.Models.Korisnik_Trener", b =>
                {
                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int>("TrenerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumTermina")
                        .HasColumnType("datetime2");

                    b.Property<int>("OdrzanoSati")
                        .HasColumnType("int");

                    b.HasKey("KorisnikID", "TrenerID", "DatumTermina");

                    b.HasIndex("TrenerID");

                    b.ToTable("Korisnik_Trener");
                });

            modelBuilder.Entity("GMS.Entities.Models.LogKretanjePoSistemu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("exceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ipAdresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isException")
                        .HasColumnType("bit");

                    b.Property<int>("korisnikID")
                        .HasColumnType("int");

                    b.Property<string>("postData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("queryPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("vrijeme")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("korisnikID");

                    b.ToTable("LogKretanjePoSistemu");
                });

            modelBuilder.Entity("GMS.Entities.Models.Nutricionist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Nutricionist");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BrojTelefona = "062709689",
                            Ime = "Marijana",
                            Prezime = "Zubac",
                            Slika = "assets/1nut.jpg"
                        },
                        new
                        {
                            ID = 2,
                            BrojTelefona = "062709689",
                            Ime = "Amela",
                            Prezime = "Ivković",
                            Slika = "assets/2nut.jpg"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Nutricionist_Seminar", b =>
                {
                    b.Property<int>("NutricionistID")
                        .HasColumnType("int");

                    b.Property<int>("SeminarID")
                        .HasColumnType("int");

                    b.HasKey("NutricionistID", "SeminarID");

                    b.HasIndex("SeminarID");

                    b.ToTable("Nutricionist_Seminar");

                    b.HasData(
                        new
                        {
                            NutricionistID = 1,
                            SeminarID = 1
                        },
                        new
                        {
                            NutricionistID = 1,
                            SeminarID = 2
                        },
                        new
                        {
                            NutricionistID = 2,
                            SeminarID = 2
                        },
                        new
                        {
                            NutricionistID = 2,
                            SeminarID = 3
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Recenzija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zanimanje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Recenzija");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ime = "Jusuf",
                            Prezime = "Nurkić",
                            Slika = "assets/1rec.jpg",
                            Tekst = "Toplo preporučujem svima koji traže vrhunsku dvoranu za fitness. Osoblje je ljubazno i obrazovano, oprema i tereni su u izvrsnom stanju, a atmosfera jako motivirajuća. To je mjesto gdje možete postići svoje fitness ciljeve i pritom se osjećati sjajno. Pridruživanje ovoj teretani bila je jedna od najboljih odluka koje sam donio za svoje zdravlje i dobrobit.",
                            Zanimanje = "Košarkaš"
                        },
                        new
                        {
                            ID = 2,
                            Ime = "Miralem",
                            Prezime = "Pjanić",
                            Slika = "assets/2rec.jpg",
                            Tekst = "Ako ste u potrazi za izvrsnom teretanom, ne tražite dalje. Dio sam ove porodice više od dvije godine i jako sam zadovoljan. Treneri su izvrsni, raznovrsnost opreme je impresivna, a sveukupno okruženje jako gostoljubivo. Vidio sam stvarne rezultate i osjećam se energičnije i sigurnije. Pridruživanje ovoj teretani bio je fantastičan izbor i ne mogu ga dovoljno preporučiti!",
                            Zanimanje = "Fudbaler"
                        },
                        new
                        {
                            ID = 3,
                            Ime = "Luka",
                            Prezime = "Modrić",
                            Slika = "assets/3rec.jpg",
                            Tekst = "Svim srcem podržavam rad ovog postrojenja kao ultimativno odredište za trening. Od najsavremenije opreme do ljubaznog osoblja koje vam pruža podršku, ova teretana ima sve što vam je potrebno za postizanje vaših fitness ciljeva. Pozitivna i motivirajuća atmosfera tjera me da se vraćam i značajno sam napredovao u svom zdravlju i kondiciji otkako sam se pridružio. Nemojte se ustručavati postati dio ove fantastične zajednice – nećete požaliti!",
                            Zanimanje = "Fudbaler"
                        },
                        new
                        {
                            ID = 4,
                            Ime = "Luka",
                            Prezime = "Dončić",
                            Slika = "assets/4rec.jpg",
                            Tekst = "Za uistinu izvanredno fitness iskustvo, ne mogu dovoljno preporučiti ovo mjesto. Ova teretana ima sve: dobro održavane sprave, stručne trenere i fantastičnu atmosferu. Vidio sam izvanredna poboljšanja u svojoj snazi i općem zdravlju otkako sam postao član. Ako tražite teretanu koja nadahnjuje i podržava vaše putovanje u fitness, onda je ovo pravo mjesto za vas. Pridruživanje je bila jedna od najboljih odluka koje sam donio za svoje zdravlje.",
                            Zanimanje = "Košarkaš"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Seminar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Predavac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Seminar");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Datum = new DateTime(2022, 12, 10, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Predavac = "Maja Gradinjan",
                            Tema = "Metabolički Sindrom"
                        },
                        new
                        {
                            ID = 2,
                            Datum = new DateTime(2023, 4, 12, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Predavac = "Darija Topić",
                            Tema = "Pravilna prehrana u službi zdravlja i sportskog razvoja"
                        },
                        new
                        {
                            ID = 3,
                            Datum = new DateTime(2020, 1, 10, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Predavac = "Tatjana Popović",
                            Tema = "Snaga u vama"
                        },
                        new
                        {
                            ID = 4,
                            Datum = new DateTime(2019, 12, 10, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Predavac = "Ivan Račić",
                            Tema = "CrossFit Level 3"
                        },
                        new
                        {
                            ID = 5,
                            Datum = new DateTime(2017, 6, 10, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Predavac = "Petar Klančir",
                            Tema = "Pro Bodybuilding"
                        },
                        new
                        {
                            ID = 6,
                            Datum = new DateTime(2022, 1, 1, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            Predavac = "Almir Tunić",
                            Tema = "Samoodbrana"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Spol", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Spol");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Naziv = "Muški"
                        },
                        new
                        {
                            ID = 2,
                            Naziv = "Ženski"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Suplement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<float>("Cijena")
                        .HasColumnType("real");

                    b.Property<int>("DobavljacID")
                        .HasColumnType("int");

                    b.Property<float>("Gramaza")
                        .HasColumnType("real");

                    b.Property<int>("KategorijaID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DobavljacID");

                    b.HasIndex("KategorijaID");

                    b.ToTable("Suplement");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Cijena = 139f,
                            DobavljacID = 1,
                            Gramaza = 2500f,
                            KategorijaID = 1,
                            Naziv = "100% Whey Protein",
                            Opis = "Muscle Freak 100% Isolate Whey Protein je visokokvalitetni izolat proteina sirutke, koji smo kreirali kako bi zadovoljili potrebe i najzahtjevnijih vježbača. Nakon godina uspješnog rada i distribucije najvećih brendova na tržištu, mi u Muscle Freaku smo odlučili da je vrijeme da i naša linija proizvoda ugleda svjetlo dana i da vam u skladu s našom tradicijom ponudimo najbolje i najkvalitetnije proizvode s predznakom bosanski brend.",
                            Slika = "assets/1sup.webp"
                        },
                        new
                        {
                            ID = 2,
                            Cijena = 99f,
                            DobavljacID = 3,
                            Gramaza = 809f,
                            KategorijaID = 1,
                            Naziv = "Gold 100% Casein",
                            Opis = "Korištenjem samo vrhunskog kazeina kao izvora proteina u svom 100% Gold Standard Casein-u, Optimum Nutrition je stvorio formulu koja postavlja standard za sve sporootpuštajuće proteine.",
                            Slika = "assets/2sup.webp"
                        },
                        new
                        {
                            ID = 3,
                            Cijena = 89f,
                            DobavljacID = 2,
                            Gramaza = 900f,
                            KategorijaID = 1,
                            Naziv = "Nitro-Tech Ripped",
                            Opis = "NITRO-TECH RIPPED™ je najnovija inovacija iz MuscleTech-a, branda koji oduševljava svojim proizvodima više od 20 godina. Ova napredna formula kombinuje proteinske peptide najviše kvalitete i izolat sa naučno testiranim sastojcima za gubitak težine. Ova 7 u 1 formula također sadrži CLA, trigliceride srednjeg lanca (MCT), L-carnitine L-tartrate, ekstrakt zelenog čaja, ekstrakt šipka i prah algi. MuscleTech® je napravio ovu jedinstvenu formula s ciljem objedinjavanja ultra-čistog proteina i gubitka težine - ovakvo nešto niste nikad prije vidjeli. Za razliku od konkurencije, svaka mjerica NITRO-TECH RIPPED™ sadrži naučno proučavanu dozu ključnih sastojaka za gubitak težine, C. canephora robusta, koja je potvrđena od strane dvije naučne studije i u čije rezultate ne morate sumnjati! Također, nevjerovatnog je okusa koji će Vas oduševiti!",
                            Slika = "assets/3sup.webp"
                        },
                        new
                        {
                            ID = 4,
                            Cijena = 139f,
                            DobavljacID = 2,
                            Gramaza = 1800f,
                            KategorijaID = 1,
                            Naziv = "Nitro-Tech Whey Protein",
                            Opis = "NITRO-TECH® je naučno istražena, pojačana proteinska formula kreirana za sve sportiste koji žele veću mišićnu masu, više snage i bolje performanse. NITRO-TECH® sadrži protein čiji primarni izvor su peptidi i izolat sirutke – dva najčistija i najkvalitetnija dostupna izvora proteina, za razliku od ostalih proteinskih suplemenata koji možda sadrže tek par gama ovih lako probavljivih i visoke biološke vrijednosti proteina. NITRO-TECH® je takođe poboljšan i sa 3g kreatin monohidrata, najistraženijim oblikom kreatina, namjenjenim za još veću mišićnu masu i snagu.",
                            Slika = "assets/4sup.webp"
                        },
                        new
                        {
                            ID = 5,
                            Cijena = 89f,
                            DobavljacID = 2,
                            Gramaza = 908f,
                            KategorijaID = 1,
                            Naziv = "Nitro-Tech 100% Whey",
                            Opis = "Preko 20 godina NITRO-TECH® je vodeći proteinski brend, izgrađen na temelju naučnih istraživanja i korištenja najmodernije tehnologija. Sada je isti istraživački i razvojni tim stvorio novu formulu whey proteina baziranu na superiornim izvorima proteina, kvaliteti i tehnici proizvodnje. Predstavljamo vam NITRO-TECH® 100% WHEY GOLD – čistu proteinsku formulu koja sadrži peptide i izolat sirutke.",
                            Slika = "assets/5sup.webp"
                        },
                        new
                        {
                            ID = 6,
                            Cijena = 119f,
                            DobavljacID = 2,
                            Gramaza = 2000f,
                            KategorijaID = 1,
                            Naziv = "Platinum 8",
                            Opis = "Vrhunska proteinska mješavina za sve namjene u bilo koje vrijeme posebno formulirana za sportiste koji žele biti na vrhuncu svoje igre. Dizajniran s visokokvalitetnom, višefaznom mješavinom proteina, može se uzimati kad god je potrebno - nakon treninga, između obroka ili prije spavanja.",
                            Slika = "assets/6sup.webp"
                        },
                        new
                        {
                            ID = 7,
                            Cijena = 35f,
                            DobavljacID = 4,
                            Gramaza = 250f,
                            KategorijaID = 2,
                            Naziv = "BCAA 2:1:1",
                            Opis = "Vrhunski ukusan spoj esencijalnih aminokiselina. Ovaj proizvod ne samo da pruža izvanredan ukus, već je i obogaćen esencijalnim hranjivim sastojcima poput vitamina C i vitamina B6. BCAA je kritičan faktor koji vam može pomoći da postignete najbolje iz svojih treninga.",
                            Slika = "assets/7sup.webp"
                        },
                        new
                        {
                            ID = 8,
                            Cijena = 45f,
                            DobavljacID = 4,
                            Gramaza = 900f,
                            KategorijaID = 2,
                            Naziv = "HMB",
                            Opis = "Self Omninutrition HMB (beta-hidroksi-beta-metilbutirat) je metabolit leucina koji sprečava razgradnju proteina i promoviše hipertrofiju mišića (povećanje ćelija koje grade tkivo); također smanjuje moguće povrede mišića nakon treninga visokog intenziteta, čime se smanjuje postotak masnoće u tijelu. Nedavna istraživanja su također pokazala da uzimanje HMB povećava mišićnu snagu, smanjuje simptome prekomjernog treninga te pozitivno utiče na VO2max (maksimalna potrošnja kiseonika). Neki stručnjaci smatraju da je VO2max ključni faktor u sportskim takmičenjima sportista. HMB je vrijedan dodatak ishrani za snagu, performanse i izdržljivost.",
                            Slika = "assets/8sup.webp"
                        },
                        new
                        {
                            ID = 9,
                            Cijena = 75f,
                            DobavljacID = 2,
                            Gramaza = 400f,
                            KategorijaID = 2,
                            Naziv = "Amino Build",
                            Opis = "Napunjene sa gradivnim elementima kako bi podržale brz oporavak. Imajući u vidu da su BCAA kao osnova u sastavu, ubrzat će period oporavka poslije treninga.",
                            Slika = "assets/9sup.webp"
                        },
                        new
                        {
                            ID = 10,
                            Cijena = 85f,
                            DobavljacID = 2,
                            Gramaza = 594f,
                            KategorijaID = 2,
                            Naziv = "Cell Tech Elite",
                            Opis = "Cell Tech Elite je visoko potentna formula koja pruža vrhunsku dozu od 5 g kreatinske matrice, koja uključuje kreatin monohidrat i kreatin hidroklorid. Osim toga, ova formula sadrži klinički dokazanu dozu od 400 mg Peak ATP-a, koji omogućava povećanje snage i veći broj ponavljanja u treningu. U kliničkoj studiji je dokazano da su ispitanici koji su koristili Peak ATP izgradili 90% više mišića u poređenju sa placebom, postižući impresivne rezultate u roku od 12 sedmica intenzivnog treninga.",
                            Slika = "assets/10sup.webp"
                        },
                        new
                        {
                            ID = 11,
                            Cijena = 85f,
                            DobavljacID = 5,
                            Gramaza = 480f,
                            KategorijaID = 2,
                            Naziv = "CW Intra Surgence",
                            Opis = "CW Intra Surgence je naučno formuliran Intra-Workout dodatak koji pruža visoko doziranu mješavinu punog spektra esencijalnih aminokiselina (EAA) i razgranatih lanaca aminokiselina (BCAA), zajedno s najnovijim hidratacijskim sastojcima i patentiranim dodacima za povećanje energije.",
                            Slika = "assets/11sup.webp"
                        },
                        new
                        {
                            ID = 12,
                            Cijena = 65f,
                            DobavljacID = 6,
                            Gramaza = 433f,
                            KategorijaID = 2,
                            Naziv = "Amino X",
                            Opis = "Amino X je specijalna aminokiselinska formula dizajnirana da pomogne tijelu u povećanju izdržljivosti tokom treninga i mišićnom oporavku nakon treninga. Sadrži kvalitetnu anaboličku mješavinu, koja spriječava katabolizam (propadanje mišićnih vlakna) te se brine za obnovu i rast mišića.",
                            Slika = "assets/12sup.webp"
                        },
                        new
                        {
                            ID = 13,
                            Cijena = 65f,
                            DobavljacID = 1,
                            Gramaza = 300f,
                            KategorijaID = 3,
                            Naziv = "Power Reactor",
                            Opis = "Muscle Freak Power Reactor je visokokvalitetni pre-workout, koji smo kreirali kako bi zadovoljili potrebe i najzahtjevnijih vježbača. Nakon godina uspješnog rada i distribucije najvećih brendova na tržištu, mi u Muscle Freaku smo odlučili da je vrijeme da i naša linija proizvoda ugleda svjetlo dana i da vam u skladu s našom tradicijom ponudimo najbolje i najkvalitetnije proizvode s predznakom bosanski brend.",
                            Slika = "assets/13sup.webp"
                        },
                        new
                        {
                            ID = 14,
                            Cijena = 85f,
                            DobavljacID = 2,
                            Gramaza = 420f,
                            KategorijaID = 3,
                            Naziv = "N.O.-Xplode Vaso",
                            Opis = "Izgradnja mišića zahtijeva pravilnu ishranu i treninge. Mnogi suplementi prije treninga mogu pružiti energiju i fokus, ali rijetko isporučuju onu pravu \"pumpu\" koju tražite. Ali sada je vaša potraga gotova zahvaljujući N.O.-XPLODE VASO!",
                            Slika = "assets/14sup.webp"
                        },
                        new
                        {
                            ID = 15,
                            Cijena = 85f,
                            DobavljacID = 7,
                            Gramaza = 410f,
                            KategorijaID = 3,
                            Naziv = "C4 Ultimate",
                            Opis = "Cellucor C4 Ultimate je dugi niz godina usavršavao pre-workoute, mnogo prije nego neki drugi brendovi u industriji sportskih suplemenata. Gotovo desetljeće brend C4® bio je prvi u kategoriji pre-workouta sa učinkom i eksplozivnom energijom, najboljim okusima, klinički proučenim sastojcima i vrhunskim formulama.",
                            Slika = "assets/15sup.webp"
                        },
                        new
                        {
                            ID = 16,
                            Cijena = 65f,
                            DobavljacID = 7,
                            Gramaza = 180f,
                            KategorijaID = 3,
                            Naziv = "C4 Ripped",
                            Opis = "C4 Ripped sadrži sličnu energetsku mješavinu kao i klasični C4, s ključnim sastojcima za energiju koji će vam pomoći da prođete kroz najteže vježbe.",
                            Slika = "assets/16sup.webp"
                        },
                        new
                        {
                            ID = 17,
                            Cijena = 69f,
                            DobavljacID = 6,
                            Gramaza = 390f,
                            KategorijaID = 3,
                            Naziv = "N.O.-Xplode",
                            Opis = "N.O.-XPLODE pomaže u održavanju mentalne budnosti i mišićne snage, donosi energiju i izdržljivost te pomaže sportistima poboljšati kapacitet na svim razinama.",
                            Slika = "assets/17sup.webp"
                        },
                        new
                        {
                            ID = 18,
                            Cijena = 69f,
                            DobavljacID = 2,
                            Gramaza = 363f,
                            KategorijaID = 3,
                            Naziv = "Shatter",
                            Opis = "MuscleTech Shatter™ je iznimno snažan i naučno osmišljen pre-workout suplement koji će Vam doslovno razderati majicu i poboljšati vaše performanse snage i izdržljivosti. Ova vrhunska formula pruža i snažnu energiju i kompleks koji će Vas potaknuti kroz svaki trening.",
                            Slika = "assets/18sup.webp"
                        },
                        new
                        {
                            ID = 19,
                            Cijena = 79f,
                            DobavljacID = 1,
                            Gramaza = 1200f,
                            KategorijaID = 4,
                            Naziv = "Mega Mass",
                            Opis = "Muscle Freak Mega Mass je visokokvalitetni gainer, koji smo kreirali kako bi zadovoljili potrebe i najzahtjevnijih vježbača. Nakon godina uspješnog rada i distribucije najvećih brendova na tržištu, mi u Muscle Freaku smo odlučili da je vrijeme da i naša linija proizvoda ugleda svjetlo dana i da vam u skladu s našom tradicijom ponudimo najbolje i najkvalitetnije proizvode s predznakom bosanski brend.",
                            Slika = "assets/19sup.webp"
                        },
                        new
                        {
                            ID = 20,
                            Cijena = 119f,
                            DobavljacID = 2,
                            Gramaza = 3200f,
                            KategorijaID = 4,
                            Naziv = "Mass Tech ELITE",
                            Opis = "Mass-Tech Elite je napredni mass gainer za one koji imaju problemasa povećanjem veličine ili žele da probiju svoje platoe snage...",
                            Slika = "assets/20sup.webp"
                        },
                        new
                        {
                            ID = 21,
                            Cijena = 89f,
                            DobavljacID = 2,
                            Gramaza = 2300f,
                            KategorijaID = 4,
                            Naziv = "100% Mass Gainer",
                            Opis = "Iz najbolje američke kompanije za prodaju suplemenata, MuscleTech predstavlja Vam 100% Mass Gainer - visokoproteinski suplement za povećanje mišične mase. Ovaj dodatak, obogaćen prirodnim i umjetnim aromama, pruža Vam sve što je potrebno da unaprijedite mišiće, snagu i performanse, uz brži oporavak mišića.",
                            Slika = "assets/21sup.webp"
                        },
                        new
                        {
                            ID = 22,
                            Cijena = 75f,
                            DobavljacID = 10,
                            Gramaza = 2270f,
                            KategorijaID = 4,
                            Naziv = "Mass Super Charger",
                            Opis = "Tesla Mass Super Charger može pomoći vašim mišićima da rastu, zahvaljujući  ugljikohidratima iz više izvora, visokom sadržaju proteina i dodatku aminokiselina u optimalnom omjeru 2:1:1 za pomoć u iskorištavanju proteina. Kreatin je također dodat kako bi pomogao da se mišići napune vodom i potakne daljnji rast, zajedno s pažljivo odabranim vitaminskim kompleksom koji podržava sposobnost vašeg tijela da koristi proteine ​​i ugljikohidrate za energiju i čistu mišićnu masu.",
                            Slika = "assets/22sup.webp"
                        },
                        new
                        {
                            ID = 23,
                            Cijena = 119f,
                            DobavljacID = 8,
                            Gramaza = 1000f,
                            KategorijaID = 4,
                            Naziv = "IsoGainz",
                            Opis = "Evolite IsoGainz je ugljikohidratno-proteinski suplement visoke kvalitete namijenjen prvenstveno aktivnim osobama koji se sastoji od: odabrani ugljikohidrati (maltodextrin sa jako malim sadržajem šećera) proteina (izolat I koncentrat koji ne sadrže laktozu) .Proizvod se može koristiti kao dodatak svakodnevnoj prehrani. Idealno prikladan za korištenje nakon treninga kako bi se nadoknadile zalihe energije u mišićima. Protein doprinosi rastu mišične mase I pomaže u njenom održavanju.",
                            Slika = "assets/23sup.png"
                        },
                        new
                        {
                            ID = 24,
                            Cijena = 159f,
                            DobavljacID = 9,
                            Gramaza = 8000f,
                            KategorijaID = 4,
                            Naziv = "Hyper Mass",
                            Opis = "Hyper Mass Professional je izuzetno moćan suplement s bogatim vitaminskim kompleksom, namijenjen da vam pomogne postići vaše ciljeve u izgradnji mišića! Ovaj preparat Hyper Mass, sa svojom vrhunskom kombinacijom sastojaka, idealan je izbor za sve koji žele dodati mišićnu masu, povećati snagu i izdržljivost tokom treninga.",
                            Slika = "assets/24sup.webp"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Teretana", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("GradID");

                    b.ToTable("Teretana");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Adresa = "Patriotske lige bb",
                            GradID = 22,
                            Naziv = "ProGym Fitness Centar"
                        },
                        new
                        {
                            ID = 2,
                            Adresa = "Novo naselje Zalik bb",
                            GradID = 18,
                            Naziv = "Bodyline Mostar"
                        },
                        new
                        {
                            ID = 3,
                            Adresa = "Turalibegova 25a",
                            GradID = 27,
                            Naziv = "Body Control"
                        },
                        new
                        {
                            ID = 4,
                            Adresa = "Veljka Mlađenovića bb",
                            GradID = 1,
                            Naziv = "Blue Line Fitness"
                        },
                        new
                        {
                            ID = 5,
                            Adresa = "Trg Alije Izetbegovića 86",
                            GradID = 30,
                            Naziv = "ZEFIT Gym"
                        },
                        new
                        {
                            ID = 6,
                            Adresa = "Sarajevska k-1",
                            GradID = 2,
                            Naziv = "Reflex Gym"
                        },
                        new
                        {
                            ID = 7,
                            Adresa = "Željeznička 2, Konjic",
                            GradID = 13,
                            Naziv = "No Limits Gym"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Trener", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Trener");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BrojTelefona = "0644076290",
                            Ime = "Kadir",
                            Prezime = "Keskin",
                            Slika = "assets/1tre.jpg"
                        },
                        new
                        {
                            ID = 2,
                            BrojTelefona = "0644076290",
                            Ime = "Azur",
                            Prezime = "Kahriman",
                            Slika = "assets/2tre.jpg"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Trener_Seminar", b =>
                {
                    b.Property<int>("TrenerID")
                        .HasColumnType("int");

                    b.Property<int>("SeminarID")
                        .HasColumnType("int");

                    b.HasKey("TrenerID", "SeminarID");

                    b.HasIndex("SeminarID");

                    b.ToTable("Trener_Seminar");

                    b.HasData(
                        new
                        {
                            TrenerID = 1,
                            SeminarID = 5
                        },
                        new
                        {
                            TrenerID = 1,
                            SeminarID = 6
                        },
                        new
                        {
                            TrenerID = 2,
                            SeminarID = 4
                        },
                        new
                        {
                            TrenerID = 2,
                            SeminarID = 6
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Administrator", b =>
                {
                    b.HasBaseType("GMS.Entities.Models.KorisnickiNalog");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("KorisnickiNalog");

                    b.HasDiscriminator().HasValue("Administrator");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Password = "admin",
                            Username = "admin",
                            Ime = "Vedad",
                            Prezime = "Keskin"
                        },
                        new
                        {
                            ID = 2,
                            Password = "host",
                            Username = "host",
                            Ime = "Džejla",
                            Prezime = "Palalić"
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.Korisnik", b =>
                {
                    b.HasBaseType("GMS.Entities.Models.KorisnickiNalog");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Korisnik_Ime");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Korisnik_Prezime");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpolID")
                        .HasColumnType("int");

                    b.Property<int>("TeretanaID")
                        .HasColumnType("int");

                    b.Property<float>("Tezina")
                        .HasColumnType("real");

                    b.Property<float>("Visina")
                        .HasColumnType("real");

                    b.HasIndex("GradID");

                    b.HasIndex("SpolID");

                    b.HasIndex("TeretanaID");

                    b.ToTable("KorisnickiNalog");

                    b.HasDiscriminator().HasValue("Korisnik");

                    b.HasData(
                        new
                        {
                            ID = 3,
                            Password = "bayern123",
                            Username = "vedadke",
                            BrojTelefona = "0644076290",
                            GradID = 18,
                            Ime = "Vedad",
                            Prezime = "Keskin",
                            Slika = "assets/1kor.png",
                            SpolID = 1,
                            TeretanaID = 2,
                            Tezina = 80f,
                            Visina = 170f
                        },
                        new
                        {
                            ID = 4,
                            Password = "fit2023",
                            Username = "dzejlap",
                            BrojTelefona = "062709689",
                            GradID = 26,
                            Ime = "Džejla",
                            Prezime = "Palalić",
                            Slika = "assets/2kor.jpg",
                            SpolID = 2,
                            TeretanaID = 2,
                            Tezina = 57f,
                            Visina = 164f
                        },
                        new
                        {
                            ID = 5,
                            Password = "fit2023",
                            Username = "saidke",
                            BrojTelefona = "0644065144",
                            GradID = 18,
                            Ime = "Said",
                            Prezime = "Keskin",
                            Slika = "assets/3kor.jpg",
                            SpolID = 1,
                            TeretanaID = 2,
                            Tezina = 62f,
                            Visina = 180f
                        },
                        new
                        {
                            ID = 6,
                            Password = "user",
                            Username = "denism",
                            BrojTelefona = "061000000",
                            GradID = 5,
                            Ime = "Denis",
                            Prezime = "Mušić",
                            Slika = "assets/4kor.jpg",
                            SpolID = 1,
                            TeretanaID = 2,
                            Tezina = 79f,
                            Visina = 186f
                        },
                        new
                        {
                            ID = 7,
                            Password = "user",
                            Username = "adilj",
                            BrojTelefona = "062000000",
                            GradID = 7,
                            Ime = "Adil",
                            Prezime = "Joldić",
                            Slika = "assets/5kor.jpg",
                            SpolID = 1,
                            TeretanaID = 2,
                            Tezina = 75f,
                            Visina = 184f
                        });
                });

            modelBuilder.Entity("GMS.Entities.Models.AutentifikacijaToken", b =>
                {
                    b.HasOne("GMS.Entities.Models.KorisnickiNalog", "korisnickiNalog")
                        .WithMany()
                        .HasForeignKey("KorisnickiNalogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("korisnickiNalog");
                });

            modelBuilder.Entity("GMS.Entities.Models.Korisnik_Clanarina", b =>
                {
                    b.HasOne("GMS.Entities.Models.Clanarina", "Clanarina")
                        .WithMany()
                        .HasForeignKey("ClanarinaID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GMS.Entities.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Clanarina");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("GMS.Entities.Models.Korisnik_Nutricionist", b =>
                {
                    b.HasOne("GMS.Entities.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GMS.Entities.Models.Nutricionist", "Nutricionist")
                        .WithMany()
                        .HasForeignKey("NutricionistID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Nutricionist");
                });

            modelBuilder.Entity("GMS.Entities.Models.Korisnik_Suplement", b =>
                {
                    b.HasOne("GMS.Entities.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GMS.Entities.Models.Suplement", "Suplement")
                        .WithMany()
                        .HasForeignKey("SuplementID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Suplement");
                });

            modelBuilder.Entity("GMS.Entities.Models.Korisnik_Trener", b =>
                {
                    b.HasOne("GMS.Entities.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GMS.Entities.Models.Trener", "Trener")
                        .WithMany()
                        .HasForeignKey("TrenerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Trener");
                });

            modelBuilder.Entity("GMS.Entities.Models.LogKretanjePoSistemu", b =>
                {
                    b.HasOne("GMS.Entities.Models.KorisnickiNalog", "korisnik")
                        .WithMany()
                        .HasForeignKey("korisnikID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("korisnik");
                });

            modelBuilder.Entity("GMS.Entities.Models.Nutricionist_Seminar", b =>
                {
                    b.HasOne("GMS.Entities.Models.Nutricionist", "Nutricionist")
                        .WithMany()
                        .HasForeignKey("NutricionistID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GMS.Entities.Models.Seminar", "Seminar")
                        .WithMany()
                        .HasForeignKey("SeminarID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Nutricionist");

                    b.Navigation("Seminar");
                });

            modelBuilder.Entity("GMS.Entities.Models.Suplement", b =>
                {
                    b.HasOne("GMS.Entities.Models.Dobavljac", "Dobavljac")
                        .WithMany()
                        .HasForeignKey("DobavljacID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GMS.Entities.Models.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Dobavljac");

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("GMS.Entities.Models.Teretana", b =>
                {
                    b.HasOne("GMS.Entities.Models.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("GMS.Entities.Models.Trener_Seminar", b =>
                {
                    b.HasOne("GMS.Entities.Models.Seminar", "Seminar")
                        .WithMany()
                        .HasForeignKey("SeminarID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GMS.Entities.Models.Trener", "Trener")
                        .WithMany()
                        .HasForeignKey("TrenerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seminar");

                    b.Navigation("Trener");
                });

            modelBuilder.Entity("GMS.Entities.Models.Korisnik", b =>
                {
                    b.HasOne("GMS.Entities.Models.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GMS.Entities.Models.Spol", "Spol")
                        .WithMany()
                        .HasForeignKey("SpolID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GMS.Entities.Models.Teretana", "Teretana")
                        .WithMany()
                        .HasForeignKey("TeretanaID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Grad");

                    b.Navigation("Spol");

                    b.Navigation("Teretana");
                });
#pragma warning restore 612, 618
        }
    }
}
